### ISSUE TITLE
Téléchargement en attente sur Uptobox et blocage des autres téléchargements

### ISSUE THREAD

**Issue by m2ok** [warkx/Synology-DownloadStation-Hosts#2]
Bonjour,

Les téléchargements Uptobox restent en attente. Il devient alors impossible de lancer un téléchargement même quelque soit la source.

Pourriez-vous voir pourquoi ?

**Comment by dummys** [comment]
Hello, il semble que l'url de login a été changé:

Ancien url : https://login.uptobox.com/log

Nouveau url: https://login.uptobox.com/logarithme

Bizarrement en local ça fonctionne, je reçois  bien mes cookies, mais sur le nas cela ne fonctionne pas. Je sais pas vraiment comment debug en directe sur le nas pour l'instant. Si l'auteur pouvait nous aider, ça serait cool.

**Comment by warkx** [comment]
Normalement c'est résolu
