### ISSUE TITLE
Probleme d'authentification 1fichier

### ISSUE THREAD

**Issue by salahtkt** [warkx/Synology-DownloadStation-Hosts#3]
Bonjour, 

Je pense que cette ligne "$queryUrl = 'https://1fichier.com/console/account.pl?user='.$Username.'&pass='.md5($Password);" pose probleme dans le code de votre module, le lien inseré de dans ne fonctionne pas. 

Le code "error" est renvoyé avec ou sans compte.

Auriez vous un autre lien pour tester le compte ? 

Cordialement,

**Comment by astark01** [comment]
A tester avec la nouvelle version, n'hesite pas a cree un nouveau "Issues" pour reporter un bug
