### ISSUE TITLE
Gestion des nouvelles url 1fichier.com !! https://1fichier.com/?1kvro6xrrl&af=111111&af=1111

### ISSUE THREAD

**Issue by LinuxArchitects** [warkx/Synology-DownloadStation-Hosts#4]
Exemple : 

https://1fichier.com/?1kvro6xrrl&af=2549450&af=2549450
Avec ce code la gestion des nouvelles url est géré tout en préservant la legacy : 

Enjoy

`private $FILEID_REGEX = '`https?:\/\/1fichier\.com\/\?([a-zA-Z0-9=&]+)\/?`i';
    private $FILEID_OLD_REGEX = '`https?:\/\/([a-z0-9A-Z]+)\.1fichier\.com\/?`i';
    private $FILE_OFFLINE_REGEX = '`BAD LINK|NOT FOUND`i';
    private $DOWNLOAD_WAIT_REGEX = '`You must wait (\d+) minutes`i';
    private $PREMIUM_REAL_URL_REGEX = '`https?:\/\/[a-z0-9]+-[a-z0-9]+\.1fichier\.com\/[a-z0-9=&]+`i';
    private $FREE_REAL_URL_REGEX = '`href=\"(https?:\/\/[a-z0-9]+-[a-z0-9]+\.1fichier\.com\/[a-z0-9&=]+)\"?`i';`

**Comment by astark01** [comment]
Normalement corrigée
