### ISSUE TITLE
Impossible de se connecter

### ISSUE THREAD

**Issue by Crocmagnon** [warkx/Synology-DownloadStation-Hosts#5]
Hello 👋 
J'ai toujours l'erreur "The account or password is invalid. Please try again."

J'ai vérifié mes identifiants, ce sont bien ceux que j'utilise pour me connecter à 1fichier.
Les mots de passe que j'ai essayé sont les suivants (en le modifiant avant sur 1fichier) :
- 64 caractères dont caractères spéciaux
- 64 caractères sans caractères spéciaux

Je préfèrerais utiliser un password avec des caractères spéciaux si possible.

**Comment by keisersuze** [comment]
Pareil. Mes accès ne fonctionnent pas non plus.

**Comment by Crocmagnon** [comment]
Des nouvelles ?

**Comment by sousouille** [comment]
J'ai testé la 3.1 mais ça ne s'installe même pas sur un ds411j.
Le 2.7.1 reconnait bien le compte mais le download ne fonctionne pas.

**Comment by Crocmagnon** [comment]
La version 3.1 fonctionne chez moi, j'ai créé le fichier avec la procédure sous Linux. Je peux me connecter et télécharger.

**Comment by LinuxArchitects** [comment]
Faut faire attention au URL des filehoster qui peuvent changer, dont un refresh du regex de temps a autre.

On peut clore l'issue ?

**Comment by Arnaudvs987** [comment]
Bonjour,

Peux-tu expliquer plus en détail le refresh du regex ? Car j’ai installé la 3.1 sur mon Synolgy mais j’ai testé le download d’un file dont le lien était ok et ça n’a pas démarré.

**Comment by LinuxArchitects** [comment]
`private $PREMIUM_REAL_URL_REGEX = '`https?:\/\/[a-z0-9]+-[a-z0-9]+\.1fichier\.com\/[a-z0-9=&]+`i';
    private $FREE_REAL_URL_REGEX = '`href=\"(https?:\/\/[a-z0-9]+-[a-z0-9]+\.1fichier\.com\/[a-z0-9&=]+)\"?`i';`

[https://github.com/LinuxArchitects/Synology-DownloadStation-Hosts/blob/master/OneFichierCom/OneFichierCom.php](LinuxArchitects)

**Comment by sousouille** [comment]
Merci pour vos réponses.  A partir de ton repo (v2.9), quand j'essaie d'importer un host que j'ai généré (soit depuis le linux du Syno soit depuis mon Windows) j'ai toujours le message _Le site d'hébergements de fichiers n'est pas valide_
C'est quoi que je foire :-) ?

**Comment by sousouille** [comment]
C'est ok pour moi avec la 3.1 en générant depuis le Linux avec la 3.1.
